version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: $FIMU_USER
      POSTGRES_PASSWORD: FIMU_PASSWORD
      POSTGRES_DB: FIMU_DB_NAME

  api:
    depends_on: 
      - db
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      FIMU_HOSTNAME: db
      FIMU_USER: $FIMU_USER
      FIMU_PASSWORD: $FIMU_PASSWORD
      FIMU_DB_NAME: $FIMU_DB_NAME
      FIMU_PORT: $FIMU_PORT
      FIMU_AUTH_SECRET: $FIMU_AUTH_SECRET
